

<?php 
$data = [
    ['id'=>100, 'ime'=>'hp1', 'naslov'=>"Harry Potter and Philosophers Stone", 'cena'=>15, 'slika'=>'img/book1.jpg', 'opis'=>'Harry Potter thinks he is an ordinary boy - until he is rescued by a beetle-eyed giant of a man, enrols at Hogwarts School of Witchcraft and Wizardry, learns to play Quidditch, and does battle in a deadly duel. The Reason, Harry Potter is a wizard!', 'grupa'=>'stare'],
    ['id'=>200, 'ime'=>'hp2', 'naslov'=>"Harry Potter and the Chamber of Secrets ", 'cena'=>20, 'slika'=>'img/book2.jpg', 'opis'=>'Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School of Witchcraft and Wizardry. But just as he is packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike. ', 'grupa'=>'stare'],
    ['id'=>300, 'ime'=>'hp3', 'naslov'=>"Harry Potter and the Prisoner of Azkaban", 'cena'=>20, 'slika'=>'img/book3.jpg', 'opis'=>"Harry Potter is lucky to reach the age of thirteen, since he has already survived the murderous attacks of the feared Dark Lord on more than one occasion. But his hopes for a quiet term concentrating on Quidditch are dashed when a maniacal mass-murderer escapes from Azkaban, pursued by the soul-sucking Dementors who guard the prison. It's assumed that Hogwarts is the safest place for Harry to be. But is it a coincidence that he can feel eyes watching him in the dark, and should he be taking Professor Trelawney's ghoulish predictions seriously?", 'grupa'=>'stara'],
    ['id'=>400, 'ime'=>'hp4', 'naslov'=>"Harry Potter and the Goblet of Fire", 'cena'=>30, 'slika'=>'img/book4.jpg', 'opis'=>"Harry Potter is in his fourth year at Hogwarts. Harry wants to get away from the pernicious Dursleys and go to the Quidditch World Cup with Hermione, Ron, and the Weasleys. He wants to find out about the mysterious event to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - not even by Wizarding standards. And in his case, different can be deadly. ", 'grupa'=>'stara'],
    ['id'=>500, 'ime'=>'hp5', 'naslov'=>"Harry Potter and the Half-Blood Prince", 'cena'=>35, 'slika'=>'img/book6.webp', 'opis'=>"It is Harry Potter 's sixth year at Hogwarts School of Witchcraft and Wizardry. As Voldemort's sinister forces amass and a spirit of gloom and fear sweeps the land, it becomes more and more clear to Harry that he will soon have to confront his destiny. But is he up to the challenges ahead of him?", 'grupa'=>'novo'],
    ['id'=>600, 'ime'=>'hp6', 'naslov'=>"Harry Potter and the Order of the Phoenix", 'cena'=>40, 'slika'=>'img/book5.jpg', 'opis'=>"Harry is in his fifth year at Hogwarts School as the adventures continue. There is a door at the end of a silent corridor. And it's haunting Harry Potter's dreams. Why else would he be waking in the middle of the night, screaming in terror? Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defence Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams.

    But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named, one that neither the magical government nor the authorities at Hogwarts can stop. As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice. His fate depends on them all.
    
    The book that took the world by storm. In his fifth year at Hogwarts, Harry faces challenges at every turn, from the dark threat of He-Who-Must-Not-Be-Named and the unreliability of the government of the magical world to the rise of Ron Weasley as the Keeper of the Gryffindor Quidditch Team. Along the way he learns about the strength of his friends, the fierceness of his enemies, and the meaning of sacrifice. ", 'grupa'=>'novo'],
    ['id'=>700, 'ime'=>'hp7', 'naslov'=>"Harry Potter and the Deathly Hallows", 'cena'=>35, 'slika'=>'img/book7.webp', 'opis'=>"Harry is waiting in Privet Drive. The Order of the Phoenix is coming to escort him safely away without Voldemort and his supporters knowing - if they can. But what will Harry do then? How can he fulfil the momentous and seemingly impossible task that Professor Dumbledore has left him?", 'grupa'=>'novo'],
    ['id'=>800, 'ime'=>'hp8', 'naslov'=>"Harry Potter and the Cursed Child", 'cena'=>30, 'slika'=>'img/book8.jpg', 'opis'=>"The book begins at King's Cross Station, with Harry's and Hermione’s respective children—Albus Potter and Rose Granger-Weasley—going off to Hogwarts for the first time. Albus is afraid he will break the family tradition and be sorted into Slytherin rather than Gryffindor. On the Hogwarts Express, Albus makes friends with Scorpius Malfoy, the son of Draco Malfoy. Scorpius is sorted into Slytherin, then in a complete surprise Albus Potter is sorted into Slytherin. Rose is sorted into Gryffindor and becomes popular as Albus shows no particular magical aptitude, thus widening the distance between her and her cousin Albus. Scorpius and Albus are friends, but rumors about Scorpius's birth cause him to be an outcast.", 'grupa'=>'novo'],
]

?>